export const linguagens = [
  '.NET', 'ACCESS', 'ACTIVE SERVER PAGES', 'ADVPL', 'AJAX', 'APEX',
  'ASSEMBLY', 'AUTHORWARE', 'AUTOLISP', 'BASIC', 'C', 'C#', 'C++',
  'CENTURA', 'CGI', 'CHILL', 'CLARION', 'CLIPPER', 'COBOL',
  'COLD FUSION', 'CSS', 'DATAFLEX', 'DBASE', 'DELPHI', 'DHTML',
  'DIRECTOR', 'DJANGO', 'DOCTRINE', 'EXCEL', 'FIREBIRD', 'FLASH',
  'FLEX', 'FLUTTER', 'FORTRAN', 'FOX PRO', 'FRAMEWORK', 'GENEXUS', 'GROOVY',
  'HTML', 'INTERBASE', 'IOS', 'JAVA', 'JAVA SCRIPT', 'JQUERY',
  'JSF', 'JSON', 'JSP', 'KYLIX', 'LABVIEW', 'LOTUS NOTES',
  'LUA', 'MAKER', 'MATLAB', 'MXML', 'MYSQL', 'NATURAL',
  'NCL', 'NODEJS', 'PASCAL', 'PERL', 'PHP', 'PL / SQL',
  'POSTGREE SQL', 'POWER BUILDER', 'PROGRESS', 'PYTHON',
  'QUICK BASIC', 'R', 'RUBY', 'SHELL SCRIPT', 'SIMULINK',
  'SQL', 'SWIFT', 'TOOLBOOK', 'TRANSACTION SQL', 'T-SQL',
  'UNIFACE', 'UNITY', 'VHDL', 'VISUAL BASIC', 'XHTML',
  'XML', 'ZIM', 'LISP', 'LINQ', 'LINGO'
];

export const camposAplicacao = [
  { id: 'AD01', descricao: 'Administr (desenvolv.organizacional, desburocratização)' },
  { id: 'AD02', descricao: 'Função Adm (Planejamento governamental: estratégico, operacional, técnica de planej., organização administr., organização funcional, organograma, estrutura organizacional, controle administr. - análise de desempenho, avaliação de desempenho)' },
  { id: 'AD03', descricao: 'Modern Adm (análise organizacional, O&M)' },
  { id: 'AD04', descricao: 'Adm Publ (Administr. Federal, Estadual, Municipal, direito administr., reforma administr., intervenção do Estado na economia, controle da administr. pública)' },
  { id: 'AD05', descricao: 'Adm Empres (administr., de negócios, privada, organização de empresas)' },
  { id: 'AD06', descricao: 'Adm Prod (planejamento da fábrica, engenharia do produto, protótipo, planejamento da produção, controle de qualidade)' },
  { id: 'AD07', descricao: 'Adm Pes (planejamento de pessoal - recrutamento, seleção, admissão, avaliação, promoção, etc)' },
  { id: 'AD08', descricao: 'Adm Materl (planejamento de material, aquisição, armazenamento, almoxarifado, alienação, controle de material, de estoque, inventário, requisição de material)' },
  { id: 'AD09', descricao: 'Adm Patrim (inventário patrimonial, fiscalização, conservação, manutenção do patrimônio)' },
  { id: 'AD10', descricao: 'Marketing (mercadologia, administr. de marketing ou mercadológica, análise, e pesquisa de mercado, estratégia de marketing, composto do produtomarca - embalagem, administr. de vendas - planejamento de vendas - controle de vendas)' },
  { id: 'AD11', descricao: 'Adm Escrit (serviços de escritório - comunicação administr., arquivo de escritório, etc)' },
  { id: 'AG01', descricao: 'Agricultur (agropecuária, desenvolvimento rural, extensão rural, planejamento e política agrícola, zoneamento agrícola)' },
  { id: 'AG02', descricao: 'Ciênc Agrl (agrologia, agronomia, agrostologia, edafologia, pomologia)' },
  { id: 'AG03', descricao: 'Adm Agricl (imóvel rural: fazenda - granja empresa rural)' },
  { id: 'AG04', descricao: 'Econom Agríc (economia agrícola)' },
  { id: 'AG05', descricao: 'Sist agríc (agricultura extensiva, intensiva, itinerante, monocultura, policultura)' },
  { id: 'AG06', descricao: 'Eng agrícl (construção rural: açude - barragem, estufa, habitação rural, drenagem irrigação)' },
  { id: 'AG07', descricao: 'Edafologia (conservação de solo, controle da erosão, melhoramento, recuperação, tratamento, manejo do solo: adubação, fertilização)' },
  { id: 'AG08', descricao: 'Fitopatol (doenças e pragas vegetais, defensivo agrícola)' },
  { id: 'AG09', descricao: 'Prod Veget (produção agrícola, fitotecnia: cultura agrícola, lavoura, cultivo - técnica agrícola)' },
  { id: 'AG10', descricao: 'Prod Animl (produto animal, zootecnia: tipos de criação, veterinária ou medicina veterinária, zoopatologia, produto veterinário; veterinária preventiva)' },
  { id: 'AG11', descricao: 'Ciênc Flor Ciências Florestais (dasonomia, economia florestal, política florestal, produção vegetal, silvicultura; arboricultura-florestamento, reflorestamento terra marginal)' },
  { id: 'AG12', descricao: 'Aquacultur (aquacultura ou aquicultura animal, vegetal)' },
  { id: 'AG13', descricao: 'Extr Veget Extrativismo vegetal (produto extrativo vegetal: celulose, cera, fibra, goma natural, madeira, látex)' },
  { id: 'AG14', descricao: 'Extr Animl Extrativismo Animal (caça, pesca, prospecção produto extrativo animal: couro-pele-pescado)' },
  { id: 'AH01', descricao: 'Assen Hum (povoamento, núcleo populacional, invasão, assentamento rural, urbano, cinturão verde)' },
  { id: 'AH02', descricao: 'Cidade (metrópole, região ou área metropolitana, rurópolis)' },
  { id: 'AH03', descricao: 'Org Territ Organização Territorial (organização do espaço, rede urbana, conurbação)' },
  { id: 'AH04', descricao: 'Políticas de Assentamento Humanos (política demográfica, migratória, planejamento familiar, política de colonização, de desenvolvimento urbano ou política urbana)' },
  { id: 'AH05', descricao: 'População (distribuição da população, mobilidade ou movimento da população, migração, dinâmica populacional)' },
  { id: 'AH06', descricao: 'Disciplinas Auxiliares (demografia, geografia urbana, agrária, teoria dos limiares ou localização, teoria da polarização)' },
  { id: 'AN01', descricao: 'Sociedade (sistema social, estrutura, situação, mobilização, controle, mudança e reforma social)' },
  { id: 'AN02', descricao: 'Desenv soc (planejamento social, política social, ação social, bem-estar social, nível ou padrão de vida)' },
  { id: 'AN03', descricao: 'Grupos soc (tribo, bando, etnia, grupo local, desenvolvimento comunitário, nação, indivíduo)' },
  { id: 'AN04', descricao: 'Cultura (civilização, cultura popular: folclore uso e costumes)' },
  { id: 'AN05', descricao: 'Religião (doutrina, teologia, prática religiosa, etc.)' },
  { id: 'AN06', descricao: 'Antropolog (antropologia física: antropometria -paleantropologia, enologia: etnografia - ernologia, etnografia, antropologia: economia - urbana - política)' },
  { id: 'AN07', descricao: 'Sociologia (sistemática, comparada aplicada: urbana - rural - política - econômica - do trabalho - da educação - do direito, sociografia, pesquisa social, processo social)' },
  { id: 'BL01', descricao: 'Biologia (ser vivo, substância orgânica, leis biológicas, biotipologia, biometria, bioclimatologia, parasitologia, filogenia ou evolução, geobiologia, histologia, limnologia)' },
  { id: 'BL02', descricao: 'Genética (citogenética, engenharia genética, genotipo, hereditariedade, melhoramento genético, gen, genética das populações)' },
  { id: 'BL03', descricao: 'Citologia (ou biologia celular, célula, meiose, etc)' },
  { id: 'BL04', descricao: 'Microbiolg (bacteriologia, virologia, biogeografia)' },
  { id: 'BL05', descricao: 'Anatomia (sistemas: cardiovascular - digestivo - tegumentar, etc, embriologia, secreção, excreção, órgãos dos sentidos)' },
  { id: 'BL06', descricao: 'Fisiologia (nascimento, digestão, reprodução, sexualidade, nemofisiologia, metabolismo)' },
  { id: 'BL07', descricao: 'Bioquímica (aminoácido, proteína, hormônio, fenômeno bioquímicos: biossíntese - fermentação - osmose, etc)' },
  { id: 'BL08', descricao: 'Biofísica (bioenergética, biomecânica, eletrofisiologia)' },
  { id: 'BT01', descricao: 'Botânica (fitologia, vegetal, vegetação, morfologia, fisiologia vegetal, quimiossíntese, genética vegetal, fitossociologia, biologia floral)' },
  { id: 'BT02', descricao: 'Fitogeograf (geografia botânica ou botânica geográfica, caatinga, cerrado, campo, mangue, etc.)' },
  { id: 'BT03', descricao: 'Botân Econ (planta condimentícia, daninha ou nociva, aromática, feculenta, têxtil, cereal, legume, hortaliça, grão alimentício)' },
  { id: 'BT04', descricao: 'Botân Sist (taxonomia vegetal)' },
  { id: 'CC01', descricao: 'Construção (construção civil: habitacional, comercial, industrial: construção industrializada ou pré-fabricada)' },
  { id: 'CC02', descricao: 'Proc Const Processo Construtivo (tradicional, convencional, misto, evoluído, cantaria, adobe, alvenaria, concreto, máquina de construção, equipamento para construção)' },
  { id: 'CC03', descricao: 'Org Constr Organização da construção (licitação de obra, custa da construção, memorial descritivo de obra, gerência de projeto de construção, execução da obra, fiscalização de obra, racionalização da construção, coordenação dimensional ...)' },
  { id: 'CC04', descricao: 'Obra Públ (engenharia civil, engenharia de avaliações, contrato de obra pública, licitação de obra pública, obra de grande porte, obra de arte; como engenharia civil)' },
  { id: 'CC05', descricao: 'Estrutura (cálculo estrutural, análise de estrutura, mecânica das estruturas: esóstica, plana, retocila, etc; tipo de estrutura: concreto, aço, metálico, inflável, etc; armadura: estrutural, armadura para concreto armado)' },
  { id: 'CC06', descricao: 'Edificação (prédio, edifício, elemento construtivo: fundação, pilar, viga, componente construtivo: painel, instalações, manutenção da construção, obra: de acabamento, melhoria, demolição)' },
  { id: 'CC07', descricao: 'Tecn Const (ancoragem, apiloagem, caleamento estrutural, cimbramento, concretagem, escoramento, terraplanagem, pavimentação)' },
  { id: 'CC08', descricao: 'Higiene das construções (ventilação, iluminação, conforto térmico isolamento: acústico, térmico, e higroscópico)' },
  { id: 'CC09', descricao: 'Eng Hidrl (obra hidráulica ou estrutura hidráulica; conduto hidráulico, tubulação, canal, reservatório: lago artificial, piscina, açude eclusa, dispositivos de controle de água: comporta, polder, reguladora de nível; barragem, drenagem ...)' },
  { id: 'CC10', descricao: 'Solo (mecânica das rochas, mecânicas dos solos, aterro, escavação, talude, movimento de terra, obra de terra; nivelamento de terra; obra de contenção: estrutura de arrimo, contenção de encosta)' },
  { id: 'CO01', descricao: 'Filosofia (metafísica, estética, ética, filosofia social, teoria do conhecimento, hermenêutica, lógica, dialética, doutrina filosófica)' },
  { id: 'CO02', descricao: 'Ciência (ciências humanas e sociais, naturais, biológicas, geociência, política científ., desenvolv. científico, história da ciência, filosofia da ciência, metodologia científica, metodologia, pesq. ou investigação, pesq. aplicada ...)' },
  { id: 'CO03', descricao: 'Ciênc Ling (linguística, geolinguística, sociolinguística e linguagem popular, linguagem: natural, artificial)' },
  { id: 'CO04', descricao: 'Comunic (comunicação humana, escrita, visual, social: comunicação de massa, propaganda, relações públicas, meios de comunicação: radiocomunicação, imprensa; pesquisa de opinião, arte gráfica: editoração, editoração, impressão, edição)' },
  { id: 'CO05', descricao: 'Arte (criação artística, patrimônio artístico, industrial, fotografia, aerofotografia, cinema, música, literatura)' },
  { id: 'CO06', descricao: 'História (política, econômica, social, pesquisa histórica: arqueologia, numismática, genealogia, filatelia, epigrafia; patrimônio histórico)' },
  { id: 'DI01', descricao: 'Legislação (federal, estadual, municipal, hierárquica das leis; constituição, lei ordinária, etc; proteção da lei ou proteção legal, hermenêutica jurídica ou interpretação das leis)' },
  { id: 'DI02', descricao: 'Direito Constitucional (poder constituinte, organização nacional: união, estado, município, distrito federal, território federal, poderes do estado; legislativo, executivo, judiciário, declaração de direitos: nacionalidade, direitos políticos ...)' },
  { id: 'DI03', descricao: 'Disc Dr. Outras Disciplinas do Direito (disciplinar, previdenciário, ecológico, urbanístico, econômico, financeiro, tributário: cálculo do tributo, evasão tributária, infração tributária, etc; direito processual civil, direito penal ...)' },
  { id: 'EC01', descricao: 'Economia (teoria econômica, metodologia da economia: modelos e econometria; análise econômica, sistema econômico)' },
  { id: 'EC02', descricao: 'An Microec (microeconomia, teoria da oferta, teoria da produção, função da produção, economias de escala, teoria dos custos, elasticidade da oferta: preço e renda; teoria da demanda ou teoria do consumidor, teoria da utilidade ou análise cardinal...)' },
  { id: 'EC03', descricao: 'Teo Microe (ou microeconomia ou teoria microeconômica, demanda agregada, oferta agregada, venda, nível de emprego)' },
  { id: 'EC04', descricao: 'Ativ Econm (setor econômico ou setor de produção, setores: primário, secundário, terciário, público, privado, informal ou economia silenciosa ou invisível ou mercado informal; fator de produção, distribuição da renda, produtividade, superprodução ...)' },
  { id: 'EC05', descricao: 'Contab Nac (ou contabilidade social ou conta nacional, agregado econômico: PIB, PNB, PNL, PIL; renda nacional, análise de insumo - produto ou input - output ou de relações intersetoriais, ou análise de Leontief, ou insumo-produto)' },
  { id: 'EC06', descricao: 'Econ Monet (moeda: criação, circulação, flutuação; sist. monetário: tipos de moeda e meios de pagto ou meio circulante; base monetária, unidade monetária, moeda divisionária; reforma monetária)' },
  { id: 'EC07', descricao: 'Mercado (demanda, oferta, mercado consumidor, mercado externo ou externo ou exterior, mercado interno, internacional, produtor, paralelo, a termo, preço)' },
  { id: 'EC08', descricao: 'Bens Econom (bens de consumo, de capital, insumo, bens: duráveis, não duráveis, tangíveis, intangíveis, inferiores, normais, de Giffen)' },
  { id: 'EC09', descricao: 'Eng/Din Ec Engenharia econômica/dinâmica econômica (análise custo/benefício ou custo benefício, pay-out ou prazo de refluxo, ciclo econômico ou flutuação econômica, nível dos preços: inflação, deflação, conjuntura econômica)' },
  { id: 'EC10', descricao: 'Econ Espec (ou ciência regional ou economia regional, economia local, urbana regionalização)' },
  { id: 'EC11', descricao: 'Propriedad (propriedade do capital, da terra ou propriedade fundiária, estrutura agrária, loteamento)' },
  { id: 'EC12', descricao: 'Ec Internac (ou relações econômicas, balanço de pagamentos: balança comercial, balança de serviços, movimento de capitais internacionais; protecionismo, livre comércio, câmbio: conversibilidade da moeda, controle cambial, câmbio livre ...)' },
  { id: 'EC13', descricao: 'Polít Econ (política fiscal, monetária, de crédito, econômica internacional, de comércio exterior, de desenvolvimento econômico, de desenvolvimento nacional, de distribuição da renda, agrária, de preços, estatização, privatização, planej. econômico)' },
  { id: 'EC14', descricao: 'Empresa (total, média, marginal, custo ou custo operacional: total, médio, etc; tipos de empresa: pública, privada, multinacional, estrangeira, microempresa, de pequeno, médio e grande porte, nacional, cooperativa; concentração econômica ...)' },
  { id: 'ED01', descricao: 'Ensin Regl Ensino regular (pré-escolar, 1º grau, 2º grau, superior, pós-graduação, orientação profissional)' },
  { id: 'ED02', descricao: 'Ensin-Supl Ensino supletivo (alfabetização, aprendizagem; comercial, industrial, agrícola, suprimento: curso de atualização, de aperfeiçoamento, treinamento)' },
  { id: 'ED03', descricao: 'Instituição/Administração/Processo de ensino (jardim escolar, escola maternal, jardim de infância, escola: de 1º grau, 2º grau, centro de ensino, de estudo supletivo, universidade, faculdade ou instituto superior de ensino, evasão escolar ...)' },
  { id: 'ED04', descricao: 'Formas de ensino/material instrucional (ensino direto, teleducação, por correspondência, radioeducação, ensino semi-indireto; módulo instrucional, equip. didático, material audio-visual aprendizagem cognitiva, psicomotora, afetiva, autodidatismo)' },
  { id: 'ED05', descricao: 'Currículo (currículo ou programa de ensino, reforma de ensino, currículo mínimo, etc; corpo docente, corpo discente, graus e diplomas)' },
  { id: 'ED06', descricao: 'Educação (pedagogia, ensino, sistema educacional, rede de ensino, educação de adulto, educação de base, de massa, etc, política educacional)' },
  { id: 'EL01', descricao: 'Ecologia (biosfera, relação biótica, relação abiótica, ecologia agrícola, aquática, florestal, equilíbrio / desequilíbrio ecológico, fenômeno ecológico)' },
  { id: 'EL02', descricao: 'Ecofisiol (ecofisiologia animal, vegetal, distrófico, digotrófico, eutrófico, etc.)' },
  { id: 'EL03', descricao: 'Ecol Human (ecodesenvolvimento, ecologia social, ecologia urbana)' },
  { id: 'EL04', descricao: 'Ecologia Vegetal/Ecologia Animal (autoecologia, sinecologia, habitat, vida selvagem)' },
  { id: 'EL05', descricao: 'Etologia (migração; anodromo, catadromo, piracema, hibernação, comportamento animal, comportamento vegetal)' },
  { id: 'EN01', descricao: 'Energia (política energética, economia energética: consumo de energia, empresa de energia)' },
  { id: 'EN02', descricao: 'Rec Energ (recursos/serviços/formas de energia: hidrelétricos, carboníferos, petrolíferos, uraníferos; serviços de energia elétrica, gás canalizado; energia elétrica, mecânica, química, radiante, luminosa ...)' },
  { id: 'EN03', descricao: 'Combustível (fóssil, de origem vegetal, biomassa, nuclear, sólido, líquido, gasoso)' },
  { id: 'EN04', descricao: 'Tecn Energ (fonte de energia: convencional, alternativa; geração, conversão, armazenamento, transporte, distribuição de energia; eletrificação, engenharia elétrica ...)' },
  { id: 'EN05', descricao: 'Eng Eletrôn (microeletrônica, circuito eletrônico, eletrônica industrial, semicondutor)' },
  { id: 'EN06', descricao: 'Eng Nucle (tecnologia de reatores, reator nuclear)' },
  { id: 'FN01', descricao: 'Finan Públ (receita pública, orçamento público, sistema tributário, despesa pública, crédito público, administração fiscal)' },
  { id: 'FN02', descricao: 'Finan Priv' },
  { id: 'FN03', descricao: 'Sist Finan (instituição financeira, operações financeiras: crédito, bancária, fiança, câmbio, sero, open market, hedge, overnight, cobrança; mercado de capitais)' },
  { id: 'FN04', descricao: 'Rec/Instrum (aplicação de recursos, capital, recursos orçamentários, fundos; orçamento: analítico, de custeio de capital, empresarial ou privado, público, de aplicação, de caixa, de receita e despesa, familiar ...)' },
  { id: 'FN05', descricao: 'Administração Financeira (juro, crédito, débito, loteria; planejamento, política, controle e análise financeira; assistência financeira, juro de mora, taxa de juro, spread; crédito: especialização geral ...)' },
  { id: 'FN06', descricao: 'Contabilid (contabilidade financeira, gerencial, técnicas contábeis, demonstração de resultado: receita/despesa, lucros e prejuízos acumulados, origens e aplicações de recursos ...)' },
  { id: 'FQ01', descricao: 'Fís Partíc (matéria/física das partículas/íons: antimatéria, valência, estados da matéria, partícula ótica, elementar, carregada, ionização)' },
  { id: 'FQ02', descricao: 'Acúst/Ótic (onda sonora, som; luz, ótica geométrica, microscópica, física, microscopia, solametria)' },
  { id: 'FQ03', descricao: 'Onda (amplitude, difração, frequência, modulação, demodulação, reflexão, refração, propagação, ressonância, tipos de onda)' },
  { id: 'FQ04', descricao: 'Metrologia (unidade de medida, dimensão, análise dimensional, equação dimensional, sistema de medida, macro e micro-medição)' },
  { id: 'FQ05', descricao: 'Mecânica (estática, dinâmica, cinemática, cinética, espaço, tempo, movimento, momento, força, densidade, massa, volume, resistência dos materiais, trabalho, potência)' },
  { id: 'FQ06', descricao: 'Física dos Sólidos/Fluídos/Plasmas (mecânica e propriedades dos sólidos, fluídos, gases, estrutura dos sólidos, hidromecânica ...)' },
  { id: 'FQ07', descricao: 'Termodinâm (calor, calorimetria, temperatura, radiação térmica, tratamento térmico, termologia, propriedades termodinâmicas)' },
  { id: "FQ08", descricao: "Eletrônica (quântica, linear, não linear)" },
  { id: 'FQ09', descricao: 'Magnetismo/Eletromagnetismo (campo, polo, circuito magnético, interferência eletromagnética, onda hertziana, micro-ondas)' },
  { id: 'FQ10', descricao: 'Física de Superfície/Dispersão (tensão superficial, capilaridade, física coloidal)' },
  { id: 'FQ11', descricao: 'Radiação (efeitos da radiação, radiação atmosférica, radiação ionizante)' },
  { id: 'FQ12', descricao: 'Espectrosc (espectrografia, espectrometria, espectroscopia atômica, molecular, ótica, espectrofotometria)' },
  { id: 'FQ13', descricao: 'Fís Molecl (física molecular/atômica, reação nuclear, estrutura molecular, radiatividade, radiometria)' },
  { id: 'FQ14', descricao: 'Química (composto químico, substância combustível, substância química, propriedade, legação, radical, reação, composição, polímero inorgânico)' },
  { id: 'FQ15', descricao: 'Química Analítica/dos polímeros (análises: calorimetria, condutometria, cromatografia; polímero orgânico/inorgânico)' },
  { id: 'FQ16', descricao: 'Fís-Quím (análise físico-química, processos físico-químicos)' },
  { id: 'FQ17', descricao: 'Quím Orgân (composto orgânico, ácido, sal)' },
  { id: 'FQ18', descricao: 'Quím Inorg (elemento químico, metal, gases raros, terras raras, composto inorgânico, nuclídeo)' },
  { id: 'GC01', descricao: 'Geog Físic (fisiografia, paleografia, geomorfologia, acidentes geográficos, morfologia genética/fisiológica)' },
  { id: 'GC02', descricao: 'Geog Humana (antropogeografia, geografia econômica, política, da população)' },
  { id: 'GC03', descricao: 'Geog Regio (regiões homogêneas, zonas geográficas: tórrida, subtropical)' },
  { id: 'GC04', descricao: 'Orient Geo (pontos cardeais, colaterais, hemisfério)' },
  { id: 'GC05', descricao: 'Geodesia (astronômica, espacial, gravimétrica, geométrica, levantamento geodésico)' },
  { id: 'GC06', descricao: 'Topografia (topometria, planimetria, altimetria, acidentes topográficos, sensoriamento/monitoramento remoto)' },
  { id: "GC07", descricao: "Fotogramet (fotogrametria terrestre, aerofotogrametria, etc)" },
  { id: "GC08", descricao: "Mapeamento (fotogramia, mapa, carta, fotocarta, mosaico, etc)" },
  { id: "GC09", descricao: "Métodos e Processos de Cartografia (astrogeodésico, método das direções, Schreiber, Sterneck, etc)" },
  { id: "GC10", descricao: "Plano Cartográfico (azimute, posição, ponto meridiano, paralelo, círculo horário, triângulo de posição, polo geográfico/celeste/elevado ...)" },
  { id: "GL01", descricao: "Geol Físic (dinâmica externa: intemperismo, erosão; dinâmica interna: tectonismo, magma; estrutura geológica: anticlinal, sinclinal ...)" },
  { id: "GL02", descricao: "Glaciolog (ou criologia, glaciação, moraina)" },
  { id: "GL03", descricao: "Geotectonc (tectônica, geodinâmica, sismologia)" },
  { id: "GL04", descricao: "Geol Marin (geologia marinha, fotogeologia, mapeamento geológico)" },
  { id: "GL05", descricao: "Geol Hist (paleontologia, arcabouço tectônico, sedimentologia, estratigrafia)" },
  { id: "GL06", descricao: "Geol Econ (petrologia, petrografia, gênese de jazida: metalgenia, mineralização, prospecção, mineralogia física/química)" },
  { id: "GL07", descricao: "GeoQuiFiTe (geoquímica, hidrogeologia, geofísica, geotécnica: solos, rochas, água subterrânea, sísmica, gravimetria, ensaios geotécnicos)" },
  { id: "HB01", descricao: "Habitação (moradia, função habitacional, mercado, política habitacional)" },
  { id: "HB02", descricao: "Tipol Habt (tipologia habitacional: unifamiliar, multifamiliar, funcional, especial, provisória: alojamento, tugúrio, móvel, flutuante)" },
  { id: "HD01", descricao: "Hidrologia (água, ciclo hidrológico)" },
  { id: "HD02", descricao: "Hidrograf (bacia hidrográfica, área de inundação, curso d’água, bacia lacustre, etc)" },
  { id: "HD03", descricao: "Hidrometr (fluviometria, pluviometria, evapometria, sedimentometria, estação hidrométrica/fluviométrica)" },
  { id: "HD04", descricao: "Oceanograf (ou oceanologia, talassografia, oceanos, tipos: física, química, biológica, geológica, batimetria)" },
  { id: "IF01", descricao: "Informação (científica, tecnológica, bibliográfica, estratégica, dados, etc)" },
  { id: "IF02", descricao: "Documentaç (análise, processamento, armazenamento, recuperação, disseminação, intercâmbio, bibliofilia, bibliologia, bibliometria)" },
  { id: "IF03", descricao: "Reprograf (fotocópia, microfotografia, microfilmagem, micrografia)" },
  { id: "IF04", descricao: "Documento (informação registrada, científica, confidencial, primária, secundária, não convencional, multimeios, máquina-legível)" },
  { id: "IF05", descricao: "Biblioteco (administração de biblioteca, processos técnicos)" },
  { id: "IF06", descricao: "Arquivolog (ou arquivística, administração de arquivos)" },
  { id: "IF07", descricao: "Ciênc Info (sistema de informação, rede, teoria e fluxo de informação)" },
  { id: "IF08", descricao: "Serv Info (biblioteca, centro de documentação, arquivo, centro referencial, museu)" },
  { id: "IF09", descricao: "Uso Inform (usuário, estudo e perfil do usuário)" },
  { id: "IF10", descricao: "Genérico (processamento de dados)" },
  { id: "IN01", descricao: "Indústria (política industrial, concentração industrial, produção industrial, pesquisa industrial, empresa industrial)" },
  { id: "IN02", descricao: "Tecnologia (política tecnológica, cooperação técnica, pesquisa tecnológica, inovação tecnológica, tecnologia apropriada, química tecnológica)" },
  { id: "IN03", descricao: "Engenharia (desenho técnico, engenharia metalúrgica, engenharia química, mecânica, automotiva, aeronáutica, naval, de produção, de teste)" },
  { id: "IN04", descricao: "Ind Ext Mi (indústria extrativa mineral: política mineral, pesquisa mineral, engenharia e minas, mineração, extrativismo mineral, exploração mineral)" },
  { id: "IN05", descricao: "Indústria de Transformação (indústria manufatureira, produto, industrialização, processo industrial, gênero da indústria: metalúrgica, elétrica, eletrônica, química, mecânica, componentes, armamento, têxtil, etc)" },
  { id: "MA01", descricao: "Meio Amb (meio ambiente artificial, natural, política ambiental)" },
  { id: "MA02", descricao: "Recurs Nat (conservação da natureza, recursos naturais renováveis, não renováveis, área protegida)" },
  { id: "MA03", descricao: "Poluição (tipos: atmosférica, bacteriológica, física, do solo, água, química, radioativa, sonora; controle e prevenção, nível de poluição, poluentes)" },
  { id: "MA04", descricao: "Qualid Amb (qualidade de vida, da água, do ar, monitoramento ambiental, engenharia ambiental, defesa civil)" },
  { id: "ME01", descricao: "Metodolg (física, dinâmica, aplicada)" },
  { id: "ME02", descricao: "Atmosfera (ar, circulação e pressão atmosférica, previsão do tempo, ventos, tempestades, radiação solar, temperatura, umidade)" },
  { id: "ME03", descricao: "Climatolog (clima, aclimatação, agroclimatologia, estação climatológica, tipos de clima)" },
  { id: "MT01", descricao: "Lógica Mat (metamatemática, método matemático, processo matemático, teoria lógica)" },
  { id: "MT02", descricao: "Álgebra (teoria dos conjuntos, teoria dos números, álgebra elementar, estrutura algébrica)" },
  { id: "MT03", descricao: "Geometria (plana, sólida, analítica, trigonometria, descritiva, diferencial, etc)" },
  { id: "MT04", descricao: "Anális Mat (topologia, análise real, numérica, complexa, vetorial, matricial, tensorial, funcional, equações integrais)" },
  { id: "MT05", descricao: "Cálculo (diferencial, integral, operacional, vetorial, matricial, tensorial, numérico, variacional)" },
  { id: "MT06", descricao: "Mat Aplic (modelo matemático: estatística, gráficos, probabilidade, análise estatística, pesquisa operacional, matemática financeira, atuarial)" },
  { id: "PD01", descricao: "Pedologia (ciência do solo; terra, solo: mineral ou orgânico)" },
  { id: "PD02", descricao: "Pedogênese (fatores de formação do solo, processo pedogenético, perfil do solo: morfologia, física, química, biologia, mineralogia)" },
  { id: "PD03", descricao: "Tipos de Solo" },
  { id: "PL01", descricao: "Ciênc Pol (teoria política, metodologia política)" },
  { id: "PL02", descricao: "Política (sistema político, estrutura política, estado-nação, formas de estado e governo, regime político, poder público, organização e ação política, doutrinas políticas)" },
  { id: "PR01", descricao: "Previdênc (seguridade social, política previdenciária, previdência pública e privada)" },
  { id: "PR02", descricao: "Benef Prev (aposentadoria, auxílio ou assistência previdenciária, pecúlio, abono, etc)" },
  { id: "PR03", descricao: "Assist Soc (médica, odontológica, alimentar, reeducativa, habitacional, organizações de assistência social, serviço social)" },
  { id: "PS01", descricao: "Psicologia (comportamento, psicologia do desenvolvimento, social, clínica, educacional, psicoterapia, processos cognitivos)" },
  { id: "PS02", descricao: "Comportamt (conduta ou comportamento humano; motivação)" },
  { id: "PS03", descricao: "Teor Psic (teorias e sistemas da psicologia, parapsicologia, behaviorismo, existencialismo, reforço, etc)" },
  { id: "SD01", descricao: "Saúde (política de saúde, higiene, saúde física, mental e pública)" },
  { id: "SD02", descricao: "Adm Sanit (administração de saúde, hospitais, postos de saúde, centros médicos, levantamento sanitário, campanhas, educação sanitária, equipamentos)" },
  { id: "SD03", descricao: "Doença (congênitas, infecciosas, do sistema reprodutor, glandular, etc)" },
  { id: "SD04", descricao: "Defic Fís (deficiências físicas e mentais, invalidez)" },
  { id: "SD05", descricao: "Assist Méd (assistência médica hospitalar, domiciliar, ambulatorial, sanitária)" },
  { id: "SD06", descricao: "Terap Diag (terapias e diagnósticos médicos: fisioterapia, hemoterapia, dietas, exames laboratoriais, radiológicos, etc)" },
  { id: "SD07", descricao: "Medicina (alopática, homeopática, preventiva, tropical, nuclear, medicina do trabalho, legal, de urgência)" },
  { id: "SD08", descricao: "Especialidades Médicas (cardiologia, endocrinologia, epidemiologia, ginecologia, oftalmologia, psiquiatria, patologia, dermatologia, radiologia, medicina alternativa)" },
  { id: "SD09", descricao: "Engenharia Biomédica (bioengenharia, biotecnologia, enfermagem, optometria, fonoaudiologia)" },
  { id: "SD10", descricao: "Farmacolog (assistência farmacêutica, toxicologia, farmacopeia, farmacognosia, medicamentos)" },
  { id: "SD11", descricao: "Odontolog (saúde oral, periodontia, prótese dentária, assistência odontológica)" },
  { id: "SM01", descricao: "Saneamento (engenharia sanitária, saneamento básico)" },
  { id: "SM02", descricao: "Resíduo (detrito, dejeto, efluente; resíduos gasosos, líquidos, orgânicos, químicos, térmicos, tóxicos)" },
  { id: "SM03", descricao: "Limpeza (pública, urbana, drenagem urbana, coleta e destinação do lixo)" },
  { id: "SM04", descricao: "Abast água (sistema de abastecimento de água; captação, adução, tratamento, reservatórios, distribuição, medição)" },
  { id: "SM05", descricao: "Esgoto (serviço de esgoto sanitário, tratamento: preliminar a terciário; remoção de sólidos, lodo, esgoto industrial)" },
  { id: "SV01", descricao: "Serviços (públicos e privados: telefonia, correios, energia, segurança, vigilância, reparo, manutenção, hospedagem, alimentação)" },
  { id: "SV02", descricao: "Seguro (social, privado, pessoal, patrimonial, de responsabilidade; seguradoras, resseguros, co-seguros, corretoras)" },
  { id: "SV03", descricao: "Comércio (interno, externo, ilícito, corretagem, intercâmbio, especulação, zona franca, política comercial)" },
  { id: "SV04", descricao: "Turismo (turismo interno, externo, intercâmbio, infraestrutura: agências, rede hoteleira)" },
  { id: "TB01", descricao: "Trabalho (intelectual, técnico, manual, mecanizado, rural, doméstico, eventual, método e controle do trabalho)" },
  { id: "TB02", descricao: "Rec Human (recursos humanos, trabalhador rural, autônomo, não qualificado, operário, classe trabalhadora)" },
  { id: "TB03", descricao: "Merc Trab (mercado de trabalho, política de emprego e salário, desemprego, fiscalização e racionalização do trabalho)" },
  { id: "TB04", descricao: "Condições de Trabalho (ergonomia, engenharia humana, ambiente de trabalho)" },
  { id: "TB05", descricao: "Estrutura Ocupacional (ocupações, profissões, sindicatos, conselhos profissionais, empresariado)" },
  { id: "TB06", descricao: "Lazer (renovação, colônia de férias, recreação)" },
  { id: "TC01", descricao: "Telecom (política e modelos de telecomunicações)" },
  { id: "TC02", descricao: "Sist Telec (sistemas de comunicação: TV, rádio, telefonia, radar, telemetria, transmissão de dados, comunicação por fio)" },
  { id: "TC03", descricao: "Eng Telec (engenharia de telecomunicações: linha de comunicação, recepção, transmissão)" },
  { id: "TC04", descricao: "Serv/Redes (serviços, redes, estações e equipamentos de telecomunicações)" },
  { id: "TP01", descricao: "Transporte (política e planejamento de transporte)" },
  { id: "TP02", descricao: "Sist Trans (sistemas de transporte doméstico, urbano, rural, integrado; infraestrutura: viária, aeroviária, dutoviária, hidroviária)" },
  { id: "TP03", descricao: "Serv Trans (transporte de carga e passageiros, linhas, empresas de transporte)" },
  { id: "TP04", descricao: "Eng Transp (engenharia de tráfego, ferroviária, rodoviária, naval, automotiva, aeronáutica)" },
  { id: "TP05", descricao: "Mod Transp (modalidades de transporte: aéreo, terrestre, hidroviário, dutoviário, vertical)" },
  { id: "UB01", descricao: "Urbanismo (arte urbana, projeto urbanístico, forma urbana, planejamento, história do urbanismo)" },
  { id: "UB02", descricao: "Solo urban (imóvel e terreno urbano, parcelamento do solo, cadastro e avaliação imobiliária, tributação, especulação)" },
  { id: "UB03", descricao: "Área urban (estrutura urbana, urbanização, uso e apropriação do solo, zoneamento, renda imobiliária)" },
  { id: "UB04", descricao: "Circ Urban Circulação Urbana (via de circulação, terminal de transporte, tráfego urbano; infraestrutura urbana: equipamento urbano, serviços públicos urbanos, equipamento comunitário)" },
  { id: "UB05", descricao: "Arquitetur (projeto de arquitetura, reconversão de uso; arquitetura: doméstica, industrial, comercial, administrativa, institucional, militar, tradicional, de interiores; elementos formais, funcionais e decorativos)" },
];

export const tiposPrograma = [
  { id: "AP01", descricao: "Aplicativos" },
  { id: "AP02", descricao: "Planejamento" },
  { id: "AP03", descricao: "Controle" },
  { id: "AP04", descricao: "Auditoria" },
  { id: "AP05", descricao: "Contabiliz" },
  { id: "AT01", descricao: "Automação" },
  { id: "AT02", descricao: "Automação de Escritório" },
  { id: "AT03", descricao: "Automação Comercial" },
  { id: "AT04", descricao: "Automação Bancária" },
  { id: "AT05", descricao: "Automação Industrial" },
  { id: "AT06", descricao: "Controle de Processos" },
  { id: "AT07", descricao: "Automação da Manufatura (Controle Numérico Computadorizado, Robótica, etc)" },
  { id: "AT08", descricao: "Eletrônica Automotiva (computador de bordo, sistema de injeção e/ou ignição eletrônica, etc)" },
  { id: "DS04", descricao: "Desv c/Metd Aplicativos Desenvolv. Sist. de acordo com determ. Metodologia" },
  { id: "DS05", descricao: "Bibliotecas de Rotinas (\"Libraries\")" },
  { id: "DS06", descricao: "Apoio à Programação" },
  { id: "DS07", descricao: "Suporte à Documentação" },
  { id: "DS08", descricao: "Conversor de Sistemas" },
  { id: "ET01", descricao: "Entretenimento" },
  { id: "ET02", descricao: "Jogos Animados (\"arcade games\")" },
  { id: "ET03", descricao: "Geradores de Desenhos" },
  { id: "ET04", descricao: "Simuladores - Simuladores Destinados ao Lazer" },
  { id: "FA01", descricao: "Ferramenta de Apoio" },
  { id: "FA02", descricao: "Processadores de Texto" },
  { id: "FA03", descricao: "Planilhas Eletrônicas" },
  { id: "FA04", descricao: "Geradores de Gráficos" },
  { id: "GI01", descricao: "Gerenciador de Informações" },
  { id: "GI02", descricao: "Gerenciador de Banco de Dados" },
  { id: "GI03", descricao: "Gerador de Telas" },
  { id: "GI04", descricao: "Gerador de Relatórios" },
  { id: "GI05", descricao: "Dicionário de Dados" },
  { id: "GI06", descricao: "Entrada e Validação de Dados" },
  { id: "GI07", descricao: "Organização, Tratamento, Manutenção de Arquivos" },
  { id: "GI08", descricao: "Recuperação de Dados" },
  { id: "IA01", descricao: "Inteligência Artificial" },
  { id: "IA02", descricao: "Sistemas Especialistas" },
  { id: "IA03", descricao: "Sistemas de Processamento de Linguagem Natural" },
  { id: "IT01", descricao: "Instrumentação" },
  { id: "IT02", descricao: "Instrumentação de Teste e Medição" },
  { id: "IT03", descricao: "Instrumentação Biomédica" },
  { id: "IT04", descricao: "Instrumentação Analítica" },
  { id: "LG01", descricao: "Linguagens" },
  { id: "LG02", descricao: "Compilador" },
  { id: "LG03", descricao: "Montador" },
  { id: "LG04", descricao: "Pré-Compilador" },
  { id: "LG05", descricao: "Compilador Cruzado" },
  { id: "LG06", descricao: "Pré-Processador" },
  { id: "LG07", descricao: "Interpretador" },
  { id: "LG08", descricao: "Linguagem Procedural" },
  { id: "LG09", descricao: "Linguagem Não Procedural" },
  { id: "PD01", descricao: "Segurança e Proteção de Dados" },
  { id: "PD02", descricao: "Senha" },
  { id: "PD03", descricao: "Criptografia" },
  { id: "PD04", descricao: "Manutenção da Integridade dos Dados" },
  { id: "PD05", descricao: "Controle de Acessos" },
  { id: "SM01", descricao: "Simulação e Modelagem" },
  { id: "SM02", descricao: "Simulador - Simulador Vôo/Carro/Submarino/..." },
  { id: "SM03", descricao: "Simuladores de Ambiente Operacional" },
  { id: "SM04", descricao: "CAE/CAD/CAM - CAE/CAD/CAM/CAL/CBT/..." },
  { id: "SO01", descricao: "Sistema Operacional" },
  { id: "SO02", descricao: "Interface de Entrada e Saída" },
  { id: "SO03", descricao: "Interface Básica de Disco" },
  { id: "SO04", descricao: "Interface de Comunicação" },
  { id: "SO05", descricao: "Gerenciador de Usuários" },
  { id: "SO06", descricao: "Administrador de Dispositivos" },
  { id: "SO07", descricao: "Controlador de Processos" },
  { id: "SO08", descricao: "Controlador de Redes" },
  { id: "SO09", descricao: "Processador de Comandos" },
  { id: "TC01", descricao: "Aplicações Técnico-Científicas" },
  { id: "TC02", descricao: "Pesquisa Operacional" },
  { id: "TC03", descricao: "Reconhecimento de Padrões" },
  { id: "TC04", descricao: "Processamento de Imagem" },
  { id: "TI01", descricao: "Teleinformática" },
  { id: "TI02", descricao: "Terminais" },
  { id: "TI03", descricao: "Dados Transmissão de Dados" },
  { id: "TI04", descricao: "Dados Comutação de Dados" },
  { id: "UT01", descricao: "Utilitários" },
  { id: "UT02", descricao: "Compressor de Dados" },
  { id: "UT03", descricao: "Conversor Meios de Armazenamento" }  
]; 